import { MoodItemType, EmojiVariantType } from "@/types";

export const MOODS_LIST: MoodItemType[] = [
  {
    id: "mood_1",
    scaleValue: 1,
    name: "@$#%&*!",
    emoji: "😡",
    animatedEmojiVariant: "angry",
  },
  {
    id: "mood_2",
    scaleValue: 2,
    name: "Unhappy",
    emoji: "😢",
    animatedEmojiVariant: "cry",
  },
  {
    id: "mood_3",
    scaleValue: 3,
    name: "Slightly unhappy",
    emoji: "😞",
    animatedEmojiVariant: "sad",
  },
  {
    id: "mood_4",
    scaleValue: 4,
    name: "Neutral",
    emoji: "😐",
    animatedEmojiVariant: "neutral-face",
  },
  {
    id: "mood_5",
    scaleValue: 5,
    name: "Slightly happy",
    emoji: "😌",
    animatedEmojiVariant: "relieved",
  },
  {
    id: "mood_6",
    scaleValue: 6,
    name: "Happy",
    emoji: "😀",
    animatedEmojiVariant: "smile",
  },
  {
    id: "mood_7",
    scaleValue: 7,
    name: "Excellent mood",
    emoji: "🤩",
    animatedEmojiVariant: "star-face",
  },
];

export const EMOJI_VARIANT_NAMES_LIST: EmojiVariantType[] = [
  "angry-symbols",
  "angry",
  "cool",
  "cry",
  "grinning",
  "heart-eyes",
  "heart-face",
  "laughing",
  "loud-cry",
  "monocle",
  "neutral-face",
  "no-mouth",
  "party-face",
  "pleading",
  "relieved",
  "sad",
  "smile",
  "star-face",
];

export const LANDING_PAGE_MOODS: Record<string, number> = {
  "0": 2,
  "1": 5,
  "2": 7,
  "3": 1,
  "4": 3,
  "5": 2,
  "6": 7,
  "7": 1,
  "8": 5,
  "9": 3,
  "10": 2,
  "11": 4,
  "12": 1,
  "13": 3,
  "14": 5,
  "15": 2,
  "16": 6,
  "17": 1,
  "18": 3,
  "19": 6,
  "20": 2,
  "21": 4,
  "22": 1,
  "23": 7,
  "24": 5,
  "25": 3,
  "26": 4,
  "27": 2,
  "28": 1,
  "29": 2,
  "30": 6,
  "31": 1,
  "32": 3,
  "33": 5,
  "34": 2,
  "35": 7,
  "36": 1,
  "37": 5,
  "38": 3,
  "39": 2,
  "40": 5,
  "41": 6,
  "42": 1,
  "43": 3,
};
